name: rcs_demo_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.1.2
  web_socket_channel: ^2.4.0
  provider: ^6.1.1
  uuid: ^4.2.1
  video_player: ^2.8.1
  chewie: ^1.7.1
  google_generative_ai: ^0.2.2
  file_picker: ^8.0.0+1
  gradient_borders: ^1.0.0
  cached_network_image: ^3.3.0
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  flutter_cache_manager: ^3.3.1
  path: ^1.8.3
  crypto: ^3.0.3
  url_launcher: ^6.2.2
  mime: ^1.0.4
  shimmer: ^3.0.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_animate: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/