name: rcs_demo_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.0
  http_parser: ^4.0.2
  file_picker: ^6.1.1
  cached_network_image: ^3.3.1
  video_player: ^2.8.2
  url_launcher: ^6.2.4
  chewie: ^1.7.5
  path_provider: ^2.1.2
  provider: ^6.1.1
  mime: ^1.0.4
  path: ^1.8.3
  video_compress: ^3.1.2
  crypto: ^3.0.3
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true